### ISSUE TITLE
Performance?

### ISSUE THREAD

**Issue by tbrannam** [alexbirkett/kiwi-java#1]
Have you found the performance to be better than Pybee's solver?   Or is it too early to compare?

**Comment by alexbirkett** [comment]
I'm currently not sure to be honest. I ported the `Benchmarks` class from the Cassowary project and the performance does not appear to be orders of magnitude better running on my mac.

**Comment by alexbirkett** [comment]
The tests ported from the Cassowary project now pass so it would be interesting to take this project for a test drive. I'm thinking of using it with [Cassowary Layout Android](https://github.com/alexbirkett/android-cassowary-layout)

**Comment by alexbirkett** [comment]
I've made a fork of Casswoary Layout Android that uses Kiwi java. This might help with performance comparisons https://github.com/alexbirkett/android-cassowary-layout/tree/kiwi.

**Comment by yongsunCN** [comment]
FYI, I recently switched from the original cassowary repo to this kiwi library for one of my projects, and it seemed that the performance had a huge improvement. I haven't got time to do a benchmark test yet, and the improvement might indeed come from other changes/optimizations of my implementation (because kiwi code is much simpler so I had some refactoring on some other parts of my project). Well, just leaving a feedback for now and I'll come back to update this feedback when I have a chance to benchmark it.
